using Microsoft.CodeAnalysis.Text;
using Microsoft.CodeAnalysis;
using System.CodeDom.Compiler;
using System.Globalization;
using System.IO;
using System.Threading;
using System.Diagnostics;

namespace FileGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class FileGeneratorClass : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<FileConfig> txtFiles =
            context.AdditionalTextsProvider
                .Where(text => text.Path.EndsWith(".txt"))
                .Select(GetDocument)
                .Where((document) => document is not null)!;

        context.RegisterSourceOutput(txtFiles, Execute);
    }

    private FileConfig? GetDocument(AdditionalText additionalText, CancellationToken cancellationToken)
    {
        //if (!Debugger.IsAttached) Debugger.Launch();
        SourceText? text = additionalText.GetText(cancellationToken);
        if (text is null)
        {
            return null;
        }

        return new FileConfig(Path.GetFileNameWithoutExtension(additionalText.Path), text.ToString());
    }

    private void Execute(SourceProductionContext context, FileConfig fileConfig)
    {
        using StringWriter writer = new(CultureInfo.InvariantCulture);
        using IndentedTextWriter tx = new(writer);

        tx.WriteLine("// <auto-generated/>");
        tx.WriteLine("#nullable enable");
        tx.WriteLine();
        tx.WriteLine($@"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{typeof(FileGeneratorClass).Assembly.GetName().Name}"", ""{typeof(FileGeneratorClass).Assembly.GetName().Version}"")]");
        tx.WriteLine($"internal static class {fileConfig.ClassName}");
        tx.WriteLine('{');
        tx.Indent++;

        tx.WriteLine(""""
            internal static string Content() =>"""
            """");
        tx.Indent--;
        tx.WriteLine(fileConfig.Content);
        tx.WriteLine(""""
            """;
            """");

        tx.WriteLine('}');

        Debug.Assert(tx.Indent == 0);
        context.AddSource($"{fileConfig.ClassName}.g.cs", writer.ToString());
    }
}
